# Data Exploration of Stress Analysis in Social Media

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
# read the csv dataset
tips_data = pd.read_csv('tips.csv')

In [3]:
# show the data of csv file
print(tips_data)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [4]:
tips_data[['total_bill', 'sex', 'day']]

     total_bill     sex   day
0         16.99  Female   Sun
1         10.34    Male   Sun
2         21.01    Male   Sun
3         23.68    Male   Sun
4         24.59  Female   Sun
..          ...     ...   ...
239       29.03    Male   Sat
240       27.18  Female   Sat
241       22.67    Male   Sat
242       17.82    Male   Sat
243       18.78  Female  Thur

[244 rows x 3 columns]

In [5]:
# Reading rows
# tips_data.loc[2, 'total_bill']
tips_data.loc[2:7.]

   total_bill   tip     sex smoker  day    time  size
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
5       25.29  4.71    Male     No  Sun  Dinner     4
6        8.77  2.00    Male     No  Sun  Dinner     2
7       26.88  3.12    Male     No  Sun  Dinner     4

In [6]:
# total rows value and columns value
tips_data.shape

(244, 7)

In [7]:
# show columns name
tips_data.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='str')

In [8]:
# show the top 5 data of file
tips_data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [9]:
tips_data.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [10]:
# gives a statistical summary of your dataset columns.
tips_data.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

# std (standard deviation)

Measures how spread out values are.

- small std → values are close together
- large std → values vary a lot

In [11]:
# This actually runs the function and displays dataframe information.
tips_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    str
 3   smoker      244 non-null    str
 4   day         244 non-null    str
 5   time        244 non-null    str
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), str(4)
memory usage: 13.5 KB

In [12]:
# show the data types of every columns data
tips_data.dtypes

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

In [13]:
# This filters the DataFrame and returns only the rows where the smoker column is "Yes".
# tips_data.smoker == 'Yes'             ### It gives boolean value
tips_data[tips_data.smoker == 'Yes']

     total_bill   tip     sex smoker  day    time  size
56        38.01  3.00    Male    Yes  Sat  Dinner     4
58        11.24  1.76    Male    Yes  Sat  Dinner     2
60        20.29  3.21    Male    Yes  Sat  Dinner     2
61        13.81  2.00    Male    Yes  Sat  Dinner     2
62        11.02  1.98    Male    Yes  Sat  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
234       15.53  3.00    Male    Yes  Sat  Dinner     2
236       12.60  1.00    Male    Yes  Sat  Dinner     2
237       32.83  1.17    Male    Yes  Sat  Dinner     2
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[93 rows x 7 columns]

In [14]:
# This returns the number of rows where smoker is "Yes".
tips_data[tips_data.smoker == 'Yes'].shape[0]

93

In [15]:
# This returns the number of male smokers in the dataset.
tips_data[(tips_data.sex == 'Male') & (tips_data.smoker == 'Yes')].shape[0]

60

In [16]:
tips_data.day.unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [17]:
for i in ['Sun', 'Sat', 'Thur', 'Fri']:
    smokers = tips_data[(tips_data.day == i) & (tips_data.smoker == 'Yes')
    ]
    print(f'Smoker Rate by day {i} : {smokers.shape[0]}')

Smoker Rate by day Sun : 19
Smoker Rate by day Sat : 42
Smoker Rate by day Thur : 17
Smoker Rate by day Fri : 15

In [18]:
### More practical using pandas library
# tips_data[tips_data.smoker == 'Yes']['day'].value_counts()
tips_data.groupby('day')['smoker'].value_counts()

day   smoker
Fri   Yes       15
      No         4
Sat   No        45
      Yes       42
Sun   No        57
      Yes       19
Thur  No        45
      Yes       17
Name: count, dtype: int64

In [19]:
# (isnull() = same as isna())
tips_data['tip'].isnull().sum()

np.int64(0)

In [20]:
# checks how many missing (NaN) values exist in each column.
tips_data.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [21]:
# To check duplicated items
tips_data[tips_data.duplicated()]

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [22]:
# 👉 Good for checking if same bill was entered twice.
tips_data.duplicated(subset=['total_bill', 'tip', 'size', 'time'])
# tips_data.tip.duplicated().sum()

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Length: 244, dtype: bool

In [23]:
# Creating new column with total_bill_tips_ratio 
tips_data['total_bill_tips_ratio'] = (
    tips_data['total_bill']  / 
    tips_data['tip']
).round(2)

In [24]:
tips_data.head()

   total_bill   tip     sex smoker  day    time  size  total_bill_tips_ratio
0       16.99  1.01  Female     No  Sun  Dinner     2                  16.82
1       10.34  1.66    Male     No  Sun  Dinner     3                   6.23
2       21.01  3.50    Male     No  Sun  Dinner     3                   6.00
3       23.68  3.31    Male     No  Sun  Dinner     2                   7.15
4       24.59  3.61  Female     No  Sun  Dinner     4                   6.81

In [25]:
# compare the exact data within column
tips_data[tips_data.total_bill.round(2) == 16.99]

   total_bill   tip     sex smoker  day    time  size  total_bill_tips_ratio
0       16.99  1.01  Female     No  Sun  Dinner     2                  16.82

In [26]:
# Check the provided values is in inside the data 
tips_data[tips_data.total_bill.isin([16.99, 20.5, 12.75])]

   total_bill   tip     sex smoker  day    time  size  total_bill_tips_ratio
0       16.99  1.01  Female     No  Sun  Dinner     2                  16.82

In [27]:
# To show the data at index number
tips_data.at[2, 'total_bill']

np.float64(21.01)

In [28]:
# it calculates the proportion (percentage-like distribution) of each category in the sex column. Within 1 value
tips_data['sex'].value_counts(normalize=True)

# tips_data['sex'].value_counts(normalize=True) * 100            ### if we want to convert into percentage ratio

sex
Male      0.643443
Female    0.356557
Name: proportion, dtype: float64

In [29]:
tips_data[['total_bill', 'tip']].agg(['mean', 'median', 'std'])

        total_bill       tip
mean     19.785943  2.998279
median   17.795000  2.900000
std       8.902412  1.383638

In [30]:
# counts how many times each unique value appears in the sex column.
tips_data.sex.value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [31]:
tips_data.groupby('sex')[['total_bill', 'tip']].agg(['mean', 'median', 'std'])

       total_bill                        tip
             mean median       std      mean median       std
sex
Female  18.056897  16.40  8.009209  2.833448   2.75  1.159495
Male    20.744076  18.35  9.246469  3.089618   3.00  1.489102

In [32]:
# tips_data.groupby('sex')['tip'].mean()
tips_data.groupby('sex').mean(numeric_only=True)

        total_bill       tip      size  total_bill_tips_ratio
sex
Female   18.056897  2.833448  2.459770               6.715402
Male     20.744076  3.089618  2.630573               7.234013

In [33]:
# to show the unique data in required column
tips_data.day.unique()

<StringArray>
['Sun', 'Sat', 'Thur', 'Fri']
Length: 4, dtype: str

In [34]:
tips_data[['smoker','sex']].value_counts()

smoker  sex
No      Male      97
Yes     Male      60
No      Female    54
Yes     Female    33
Name: count, dtype: int64

In [35]:

tips_data[tips_data['smoker'] == 'Yes']['sex'].value_counts(normalize=True) * 100

sex
Male      64.516129
Female    35.483871
Name: proportion, dtype: float64

There are male smoker ratio is much higher than female.

In [36]:
#  Group the data by 'sex' & 'smoker' then calculate the mean for 'total_bill' & 'tip'.
tips_data.groupby(['sex', 'smoker'])[['total_bill', 'tip']].mean()

               total_bill       tip
sex    smoker
Female No       18.105185  2.773519
       Yes      17.977879  2.931515
Male   No       19.791237  3.113402
       Yes      22.284500  3.051167

This will calculate the average total bill and average tip for each combination of:

 - Male smoker
 - Male non-smoker
 - Female smoker
 - Female non-smoker

Here we can clearly see the data of tip and total bill is much more spend male than female.

In [37]:
tips_data[['tip', 'total_bill']].corr()

                 tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

#### Use correlation when you want to measure the relationship between two numeric variables.

It helps answer questions like:

- “When one variable increases, does another also increase?”
- “Are these variables related?”
- “How strongly are they connected?”

--> As bill increases, tip also increases.

---> That creates positive correlation.

So customers with larger bills tend to give larger tips.