In [1]:
import pandas as pd

titanic_df = pd.read_csv('Updated_Titanic_Data.csv')

titanic_df.head()

,PassengerId,initials,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_initials,PStatus
0,1.0,Mr,0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,False,S,Mr,3
1,2.0,Mrs,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,True,C,Mrs,1
2,3.0,Miss,1,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,False,S,Miss,3
3,4.0,Mrs,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,True,S,Mrs,1
4,5.0,Mr,0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,False,S,Mr,3

# apply, map, aggregate function

# apply
- DataFrame.apply(func, axis=0) calls func on each column by default. With axis=1, it calls func on each row. Series.apply(func) calls func on each element (or the whole Series, depending on signatures in recent versions).

In [2]:
# apply

# def get_initial(name):
#     return name.split(",")[-1].split(".")[0].strip()

get_initial = lambda name: name.split(",")[-1].split(".")[0].strip()

titanic_df.Name.apply(get_initial)

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
884     Rev
885    Miss
886    Miss
887      Mr
888      Mr
Name: Name, Length: 889, dtype: str

In [3]:
get_initial = lambda name: name.split(",")[-1].split(".")[0].strip()

titanic_df.Name.map(get_initial)

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
884     Rev
885    Miss
886    Miss
887      Mr
888      Mr
Name: Name, Length: 889, dtype: str

In [4]:
get_max = lambda values: values.max()

titanic_df.Age.aggregate(["mean", "sum", get_max])

mean           29.347773
sum         26090.170000
<lambda>       80.000000
Name: Age, dtype: float64

# Handling Incorrect Data

In [5]:
import numpy as np


data = pd.DataFrame({
    "id":[1,3,5,7,9],
    "name":["John","Jane","Jennifer","Johan","Jeff"],
    "age":[25,-32,19,42,"55"],
    "gender" : ["M","M","Z","F","F"],
    "income":[400, 700, 300, np.nan, 600]
})

In [6]:
data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane  -32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [7]:
data.dtypes

id          int64
name          str
age        object
gender        str
income    float64
dtype: object

In [8]:
data = data.astype({"age":"int16"})
data.age = abs(data.age)

In [9]:
data

   id      name  age gender  income
0   1      John   25      M   400.0
1   3      Jane   32      M   700.0
2   5  Jennifer   19      Z   300.0
3   7     Johan   42      F     NaN
4   9      Jeff   55      F   600.0

In [10]:
data[data.gender.isin(["M","F"])]

   id   name  age gender  income
0   1   John   25      M   400.0
1   3   Jane   32      M   700.0
3   7  Johan   42      F     NaN
4   9   Jeff   55      F   600.0

In [11]:
titanic_df

,PassengerId,initials,Survived,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_initials,PStatus
0,1.0,Mr,0,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,A/5 21171,7.2500,False,S,Mr,3
1,2.0,Mrs,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,71.2833,True,C,Mrs,1
2,3.0,Miss,1,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.9250,False,S,Miss,3
3,4.0,Mrs,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1000,True,S,Mrs,1
4,5.0,Mr,0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.0500,False,S,Mr,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,887.0,Mr,0,"Montvila, Rev. Juozas",male,27.0,0.0,0.0,211536,13.0000,False,S,Rev,2
885,888.0,Miss,1,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30.0000,True,S,Miss,1
886,889.0,Miss,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,21.5,1.0,2.0,W./C. 6607,23.4500,False,S,Miss,3
887,890.0,Mr,1,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30.0000,True,C,Mr,1
888,891.0,Mr,0,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.7500,False,Q,Mr,3